channels:
  - conda-forge
dependencies:
  - r-base=3.6
  - python=3.6
  - numpy
  - pip
  - pip:
    - matplotlib==3.1.1
    - numpy==1.16.5
    - numpydoc==0.9.1
    - plotly==4.1.0
    - scipy==1.3.1
    - seaborn==0.9.0
    - tables==3.5.2
    - urllib3==1.24.2
    - feather-format==0.4.1
    - joypy==0.2.5
    - voila==0.2.6
    - voila-gridstack==0.1.0
